[metadata]
title = "XRF Report"
author = "Mike"

[paths]
image_dir = "images"
output_pdf = "output/report.pdf"
template = "template/report_template.tex"

[images]
include_thumbnails = true
caption_prefix = "Photo"
extensions = [".png", ".tif"]

[layout]
margin_mm = 20.0
font_size_pt = 12
page_size = "Letter"
